CREATE TABLE MASTER_IMAGENES_PRODUCTOS(
  ID_PRODUCTO NUMBER,
  NOMBRE_IMAGEN VARCHAR2(150),
  EXTENSION VARCHAR2(10),
  IMAGEN BLOB
)
[18:56]
-- Script de Oracle para la tabla USUARIO
CREATE TABLE USUARIO (
    ID_USUARIO NUMBER,
    NOMBRE VARCHAR2(255),
    APELLIDO1 VARCHAR2(255),
    APELLIDO2 VARCHAR2(255),
    MAIL VARCHAR2(255),
    PASSWD VARCHAR2(255),
    ID_ROL NUMBER
);

-- Script de Oracle para la tabla ROL
CREATE TABLE ROL (
    ID_ROL NUMBER,
    DESCRIPCION VARCHAR2(255)
);

-- Script de Oracle para la tabla CITA
CREATE TABLE CITA (
    ID_CITA NUMBER,
    ID_USUARIO NUMBER,
    ID_REPARACION NUMBER,
    ID_TALLER NUMBER,
    FECHA_ENTRADA DATE,
    FECHA_SALIDA DATE,
    ESTADO VARCHAR2(255)
);

-- Script de Oracle para la tabla TALLER
CREATE TABLE TALLER (
    ID_TALLER NUMBER,
    CIF VARCHAR2(255),
    DESCRIPCION_SOCIAL VARCHAR2(255)
);

-- Script de Oracle para la tabla REPARACION
CREATE TABLE REPARACION (
    ID_REPARACION NUMBER,
    ID_CITA NUMBER,
    ID_VEHICULO_SUSTITUCION NUMBER,
    COSTE_ASOCIADO NUMBER,
    TIEMPO_EN_TALLER NUMBER
);

-- Script de Oracle para la tabla REPARACION_PIEZA
CREATE TABLE REPARACION_PIEZA (
    ID_REPARACION NUMBER,
    ID_PIEZA NUMBER,
    COSTE_ASOCIADO NUMBER,
    TIEMPO_EN_TALLER NUMBER
);

-- Script de Oracle para la tabla PIEZA
CREATE TABLE PIEZA (
    ID_PIEZA NUMBER,
    DESCRIPCION VARCHAR2(255),
    COSTE NUMBER
);

-- Script de Oracle para la tabla VEHICULO_SUSTITUCION
CREATE TABLE VEHICULO_SUSTITUCION (
    NUM_BASTIDOR_VEHICULO VARCHAR2(255),
    MARCA VARCHAR2(255),
    MODELO VARCHAR2(255),
    COLOR VARCHAR2(255),
    PRECIO_POR_DIA NUMBER,
    ID_IMAGEN NUMBER
);

-- Script de Oracle para la tabla IMAGEN_VEHICULO
CREATE TABLE IMAGEN_VEHICULO (
    ID_IMAGEN NUMBER,
      NOMBRE_IMAGEN VARCHAR2(150),
    EXTENSION VARCHAR2(10),
  IMAGEN BLOB
);

-- Script de Oracle para la tabla CONTACTO
CREATE TABLE CONTACTO (
    ID_CONTACTO NUMBER,
    NOMBRE VARCHAR2(255),
    APELLIDOS VARCHAR2(255),
    MAIL VARCHAR2(255),
    CONSULTA VARCHAR2(255),
    CONTESTADO VARCHAR2(255)
);